language: node_js
node_js:
  - "stable"
install:
  - npm install
  - npm install -g @cyclonedx/bom
before_script:
  - npm install
script:
  - npm run build
  ./update.sh
after_script:
  - rm payload.json 
